blank_issues_enabled: false
contact_links:
  - name: Nefino Contact
    url: https://www.nefino.de/kontakt
    about: For questions and further information, please feel free to contact the Nefino team.